import express from "express";
import cors from "cors";
import cookieParse from "cookie-parser";
import { errorHandler } from "./utils/error.handler.js";
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use(cookieParse());
app.use(errorHandler);
export default app;